// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renewal.DataHub.Data;

#nullable disable

namespace Renewal.DataHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250323114744_tesing08")]
    partial class tesing08
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmountReceive", b =>
                {
                    b.Property<Guid>("AmountreceivedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amountreceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("POId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AmountreceivedId");

                    b.HasIndex("POId");

                    b.ToTable("AmountReceived");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.Branch", b =>
                {
                    b.Property<Guid>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Suspend")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORYID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORYNAME");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATEDDATE");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("ISACTIVE");

                    b.Property<int?>("Suspend")
                        .HasColumnType("int")
                        .HasColumnName("Suspend");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATEDDATE");

                    b.HasKey("CategoryId");

                    b.ToTable("MS_Category");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit");

                    b.Property<int?>("Suspend")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.PODetail", b =>
                {
                    b.Property<Guid>("POId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("POID");

                    b.Property<string>("Accountable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Accountable");

                    b.Property<Guid?>("ClientNameId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientNameID");

                    b.Property<string>("ContractPeriod")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ContractPeriod");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Createddatetime");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyID");

                    b.Property<string>("DMPOC")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DMPOC");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<int?>("EngagementModelId")
                        .HasColumnType("int")
                        .HasColumnName("EngagementModelID");

                    b.Property<string>("FMPOC")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FMPOC");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("Isactive");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("JoiningDate");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("POFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("POFileName");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PONumber");

                    b.Property<int?>("POStatusId")
                        .HasColumnType("int")
                        .HasColumnName("POStatusID");

                    b.Property<int?>("POTypeId")
                        .HasColumnType("int")
                        .HasColumnName("POTypeID");

                    b.Property<decimal?>("POValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("POvalue");

                    b.Property<string>("ProposalPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProposalPath");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remarks");

                    b.Property<string>("ReminderToAlert")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RemindertoAlert");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("RenewalDate");

                    b.Property<string>("ResourceProjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResourceprojectName");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<int?>("Suspend")
                        .HasColumnType("int")
                        .HasColumnName("Suspend");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Updateddatetime");

                    b.HasKey("POId");

                    b.HasIndex("ClientNameId");

                    b.ToTable("PODetails");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.PettyCashTransaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BranchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaidTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("BranchID");

                    b.ToTable("PettyCashTransaction");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.RenewalValue", b =>
                {
                    b.Property<Guid>("RenewalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AlterTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reminder")
                        .HasColumnType("int");

                    b.Property<string>("RenewalDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Suspend")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Validity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RenewalId");

                    b.ToTable("Renewalset");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.TransactionDetails", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AlertTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Remider")
                        .HasColumnType("int");

                    b.Property<string>("RenewalDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RenewalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Suspend")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Validity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("RenewalId");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("AmountReceive", b =>
                {
                    b.HasOne("Renewal.DataHub.Models.Domain.PODetail", "PODetail")
                        .WithMany()
                        .HasForeignKey("POId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PODetail");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.PODetail", b =>
                {
                    b.HasOne("Renewal.DataHub.Models.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientNameId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.PettyCashTransaction", b =>
                {
                    b.HasOne("Renewal.DataHub.Models.Domain.Branch", "Branch")
                        .WithMany("PettyCashTransaction")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.TransactionDetails", b =>
                {
                    b.HasOne("Renewal.DataHub.Models.Domain.RenewalValue", "Renewal")
                        .WithMany()
                        .HasForeignKey("RenewalId");

                    b.Navigation("Renewal");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.Branch", b =>
                {
                    b.Navigation("PettyCashTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
