// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renewal.DataHub.Data;

#nullable disable

namespace Renewal.DataHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250312000707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORYID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORYNAME");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATEDDATE");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("ISACTIVE");

                    b.Property<int?>("Suspend")
                        .HasColumnType("int")
                        .HasColumnName("Suspend");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATEDDATE");

                    b.HasKey("CategoryId");

                    b.ToTable("MS_Category");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.PODetail", b =>
                {
                    b.Property<int>("POId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POId"));

                    b.Property<string>("Accountable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Accountable");

                    b.Property<int?>("ClientNameId")
                        .HasColumnType("int")
                        .HasColumnName("ClientNameID");

                    b.Property<string>("ContractPeriod")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ContractPeriod");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Createddatetime");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyID");

                    b.Property<string>("DMPOC")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DMPOC");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EndDate");

                    b.Property<int?>("EngagementModelId")
                        .HasColumnType("int")
                        .HasColumnName("EngagementModelID");

                    b.Property<string>("FMPOC")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FMPOC");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("Isactive");

                    b.Property<string>("JoiningDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JoiningDate");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("POFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("POFileName");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PONumber");

                    b.Property<int?>("POStatusId")
                        .HasColumnType("int")
                        .HasColumnName("POStatusID");

                    b.Property<int?>("POTypeId")
                        .HasColumnType("int")
                        .HasColumnName("POTypeID");

                    b.Property<decimal?>("POValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("POvalue");

                    b.Property<string>("ProposalPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProposalPath");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remarks");

                    b.Property<string>("ReminderToAlert")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RemindertoAlert");

                    b.Property<string>("RenewalDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RenewalDate");

                    b.Property<string>("ResourceProjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResourceprojectName");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StartDate");

                    b.Property<int?>("Suspend")
                        .HasColumnType("int")
                        .HasColumnName("Suspend");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Updateddatetime");

                    b.HasKey("POId");

                    b.ToTable("PODetails");
                });
#pragma warning restore 612, 618
        }
    }
}
