// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renewal.DataHub;

#nullable disable

namespace Renewal.DataHub.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("CLIENTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CLIENTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ISACTIVE")
                        .HasColumnType("bit");

                    b.Property<int?>("Suspend")
                        .HasColumnType("int");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("CLIENTID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.RenewalValue", b =>
                {
                    b.Property<Guid>("RENEWALID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ALERTTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BRANCHID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CATEGORYID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("REMINDER")
                        .HasColumnType("int");

                    b.Property<string>("RENEWALDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STARTDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<bool?>("SUSPEND")
                        .HasColumnType("bit");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("VALIDITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RENEWALID");

                    b.ToTable("Renewalset");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.TransactionDetails", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ALERTTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BRANCHID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CATEGORYID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("REMINDER")
                        .HasColumnType("int");

                    b.Property<string>("RENEWALDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RENEWALID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("STARTDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<bool?>("SUSPEND")
                        .HasColumnType("bit");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("VALIDITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("RENEWALID");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("Renewal.DataHub.Models.Domain.TransactionDetails", b =>
                {
                    b.HasOne("Renewal.DataHub.Models.Domain.RenewalValue", "Renewal")
                        .WithMany()
                        .HasForeignKey("RENEWALID");

                    b.Navigation("Renewal");
                });
#pragma warning restore 612, 618
        }
    }
}
